//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char cactus1 [] = {
0x18, 0x18, 0xD8, 0xD8, 0xD8, 0xF8, 0x7B, 0x1B, 0x1F, 0x1E, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18
};
