//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p1hitbr [] = {
0x60, 0x80, 0xC0, 0xE0, 0xD4, 0x4C, 0x40, 0x60, 
};
