//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p1hittl [] = {
0x00, 0x00, 0x08, 0x08, 0x70, 0x7C, 0x36, 0xDC, 
};
