//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p1hitbl [] = {
0x0E, 0x07, 0x07, 0x09, 0x08, 0x04, 0x00, 0x00, 
};
