//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p1lyingr [] = {
0x00, 0x00, 0x00, 0x00, 0x00, 0xF0, 0xF9, 0xFF, 
};
