//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p1lyingl [] = {
0x00, 0x00, 0x00, 0x00, 0x40, 0x58, 0x6D, 0xFF, 
};
