//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p2hittl [] = {
0x00, 0x00, 0x00, 0x04, 0x04, 0x0C, 0x00, 0x08, 
};
