//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p2hitbl [] = {
0x06, 0x01, 0x03, 0x07, 0x2B, 0x32, 0x02, 0x06, 
};
