//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p2hittr [] = {
0x00, 0x00, 0x10, 0x10, 0x0E, 0x3E, 0x6C, 0x3B, 
};
