//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p2hitbr [] = {
0x70, 0xE0, 0xE0, 0x90, 0x10, 0x20, 0x00, 0x00, 
};
