//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p2lyingr [] = {
0x00, 0x00, 0x00, 0x00, 0x02, 0x1A, 0xB6, 0xFF, 
};
