//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char p2lyingl [] = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x9F, 0xFF, 
};
